### ISSUE TITLE
WidgetTarget Empty for Playlists

### ISSUE THREAD

**Issue by bumpaneer** [mikesilvo164/script.skinshortcuts#74] opened 2022-01-14 19:31 UTC
@anxdpanic Perhaps you may be able to assist.

In troubleshooting why some widgets now seem to be broken for my skin, I noticed that the widgetTarget is coming back empty. I traced the changed behavior down to: https://github.com/mikesilvo164/script.skinshortcuts/commit/12562d2eb1eedf52d6a21fd08550cfba50b09c09#diff-3eb7af7688749ce58a2bcec5231231baf7ed546fc81f4f2c9426ba1bc5eefc3bR1157 . The media_content is being set to an empty string on each line iteration of the xsp parsing. This causes the variable to be blanked out before it is read for the line.tag=="name" check happens. I am not sure why the media_content variable needs to be set to an empty string, but the media_library does not, but I believe the code needs to be changed to something like:
```
                        for line in iterator:

                            if line.tag == "smartplaylist":
                                media_content = ""
```
around line 1251 in library.py

This change causes the media_content (and therefore the widgetTarget) to get set correctly.

**Comment by anxdpanic** [comment] 2022-01-14 20:18
Should be resolved in #76 
Will try to get a test zip up soon

**Comment by anxdpanic** [comment] 2022-01-14 20:46
Can you give, https://github.com/mikesilvo164/script.skinshortcuts/releases/tag/2.0.1.alpha1 a try and confirm the issue is resolved when you have some time. Thanks, in advance.

**Comment by bumpaneer** [comment] 2022-01-14 21:13
Looks good to me. Thanks for the quick update!

**Closed** 2022-01-18 19:38 UTC
