### ISSUE TITLE
script.skinshortcuts doesn't work in Kodi 19.3 Matrix with Pellucid skin - Can I install a prerelease to try to fix this?

### ISSUE THREAD

**Issue by stevenvolckaert** [mikesilvo164/script.skinshortcuts#68] opened 2021-09-15 09:17 UTC
I've installed the Pellucid skin on my Kodi 19.3 Matrix instance, which runs as an app on my nVidia SHIELD.

When I edit Pellucid's menu items and try to assign an action to a custom menu item (e.g. open one of my favorites), a window appears, titled **Install Widget Provider**, but the window only contains the OK and Cancel buttons. I would expect to be able to select something, but the window contains no items at all.

I've seen that Pellucid has a dependency on script.skinshortcuts; my guess is that the latest stable 1.x release is incompatible with Kodi 19.3.

Is this correct?

Would I be able to fix this behavior by installing a script.skinshortcuts prerelease (e.g. [2.0.0.alpha08](https://github.com/mikesilvo164/script.skinshortcuts/releases))?

Thank you very much for your help!

**Comment by eXoterr** [comment] 2021-11-26 08:24
I found temporary solution. Check [this](https://github.com/mikesilvo164/script.skinshortcuts/issues/72).

**Comment by stevenvolckaert** [comment] 2021-11-26 16:49
Thanks for the suggestion! @mikesilvo164, is this a possible solution?

**Comment by anxdpanic** [comment] 2021-11-26 16:52
Will be looking into this asap

https://mirrors.kodi.tv/addons/matrix/script.skinshortcuts/ for the old versions if needed in the meantime

**Comment by stevenvolckaert** [comment] 2021-11-26 16:55
Thank you @anxdpanic!

**Comment by anxdpanic** [comment] 2022-01-14 20:29
Should be resolved in #77

**Comment by anxdpanic** [comment] 2022-01-14 20:47
Can you guys try, https://github.com/mikesilvo164/script.skinshortcuts/releases/tag/2.0.1.alpha1 when you have a moment and confirm the issue is resolved. Thanks in advance!

**Comment by anxdpanic** [comment] 2022-01-23 22:17
Submitting 2.0.1 to official for review, if you have any issues with 2.0.1 when available please reopen/create a new issue.

**Closed by anxdpanic** 2022-01-23 22:17 UTC
